#pragma once


#define BUFSIZE 4096 

#define ESTATUS_FAILED(eStatus) (ESTATUS_SUCCESS != eStatus)

typedef enum _ESTATUS
{

	ESTATUS_INVALID = -1,
	ESTATUS_SUCCESS = 0,
	ESTATS_MISSING_ARGUMENTS,
	ESTATUS_ENUMERATION_ERROR,
	ESTATUS_GET_FILE_SECURIT_ERROR,
	ESTATUS_REG_OPEN_KEY_ERROR,
	ESTATUS_CREATE_CHILD_PROCESS_ERROR,
	ESTATUS_ASSIGN_HANDLE_ERROR,
	ESTATUS_DUPLICATE_TOKEN_ERROR,
	ESTATUS_EMPTY_PIPE
}ESTATUS;

